apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    isDefault: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: robot-sim
      defaultBucket: telemetry
    secureJsonData:
      token: robot-sim-demo-token
