apiVersion: 1

datasources:
  - name: Amazon Timestream
    type: grafana-timestream-datasource
    access: proxy
    isDefault: true
    jsonData:
      authType: default
      defaultDatabase: robot-sim-telemetry
      defaultTable: telemetry
      defaultRegion: ${AWS_DEFAULT_REGION}
